services:
  redis:
    image: redis:latest
    ports:
      - "6378:6379"
    volumes:
      - ./redis:/data
    command: redis-server --appendonly yes
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27016:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
      - MONGO_INITDB_DATABASE=my_pocket_development
    volumes:
      - ./mongo:/data/db
networks:
  default:
    external: true
    name: my_pocket
